//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMY.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorityRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuthorityRole()
        {
            this.AuthorityRoleInFunction = new HashSet<AuthorityRoleInFunction>();
            this.AuthorityUserInRole = new HashSet<AuthorityUserInRole>();
        }
    
        public System.Guid RoleGuid { get; set; }
        public string RoleName { get; set; }
        public int DisplayOrder { get; set; }
        public string RoleEnumName { get; set; }
        public string Remark { get; set; }
        public string RoleType { get; set; }
        public bool Enable { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorityRoleInFunction> AuthorityRoleInFunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorityUserInRole> AuthorityUserInRole { get; set; }
    }
}
