//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMY.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductV
    {
        public System.DateTime TimeCreated { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsRecommended { get; set; }
        public bool IsSpecialOffer { get; set; }
        public string Status { get; set; }
        public string ProductRemark { get; set; }
        public string ProductDetail { get; set; }
        public int PromotionPrice { get; set; }
        public int Price { get; set; }
        public string SaleSubTitle { get; set; }
        public string SaleTitle { get; set; }
        public string DefaultPic { get; set; }
        public int ProductNumber { get; set; }
        public System.Guid CategoryGuid { get; set; }
        public string ProductName { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
        public string CategoryName { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime TimeOnShelf { get; set; }
        public System.DateTime TimeOffShelf { get; set; }
        public int ImaginaryNumber { get; set; }
        public int VisitedTotal { get; set; }
        public int SoldTotal { get; set; }
    }
}
