//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMY.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.UserDeliveryAddress = new HashSet<UserDeliveryAddress>();
            this.UserFavorite = new HashSet<UserFavorite>();
            this.UserOperationRecords = new HashSet<UserOperationRecords>();
            this.UserShoppingCart = new HashSet<UserShoppingCart>();
        }
    
        public System.Guid Guid { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public string AvatarImgUrl { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public bool IsEmailValidated { get; set; }
        public string MobilePhone { get; set; }
        public bool IsMobilePhoneValidated { get; set; }
        public string Status { get; set; }
        public int CountVisited { get; set; }
        public string IPv4LastVisited { get; set; }
        public bool IsDeleted { get; set; }
        public string UserType { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public System.DateTime TimeLastVisited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDeliveryAddress> UserDeliveryAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavorite> UserFavorite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOperationRecords> UserOperationRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserShoppingCart> UserShoppingCart { get; set; }
    }
}
