var ContainerBridgeConfig = {
    debug: true,
    wechatJsUrl: "http://res.wx.qq.com/open/js/jweixin-1.0.0.js",
    wechatSignatureApiUrl: "http://km.wx.uxiang.cn/AdvanceApi/MerchantJsApiSignature",
    wechatAppID: "wxaa3ce740e41cf90f",
    wechatAppSecret: "4a77817827222a619eb788e1bd794eb5",
    wechatAPIList: [
        "onMenuShareTimeline",
        "onMenuShareAppMessage",
        "onMenuShareQQ",
        "onMenuShareWeibo",
        "onMenuShareQZone",
        "startRecord",
        "stopRecord",
        "onVoiceRecordEnd",
        "playVoice",
        "pauseVoice",
        "stopVoice",
        "onVoicePlayEnd",
        "uploadVoice",
        "downloadVoice",
        "chooseImage",
        "previewImage",
        "uploadImage",
        "downloadImage",
        "translateVoice",
        "getNetworkType",
        "openLocation",
        "getLocation",
        "hideOptionMenu",
        "showOptionMenu",
        "hideMenuItems",
        "showMenuItems",
        "hideAllNonBaseMenuItem",
        "showAllNonBaseMenuItem",
        "closeWindow",
        "scanQRCode",
        "chooseWXPay",
        "openProductSpecificView",
        "addCard",
        "chooseCard",
        "openCard"
    ],
    alipayJsUrl: "http://static.alipay.com/aliBridge/1.0.0/aliBridge.min.js",
    relJsUrl: "https://imapi.icbc.com.cn/icbc/jsrel1.0.6.js",
    relAppID: "",
    relSignatureApiUrl: "http://u.yibalian.cn/Center/JsApiSignature"
};